# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cplkGuEIcrn7OYYZgPgJl7D6oKdNkXaN
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


data = { "Game": ["GTA 5", "spider-man", "fifa 26", "god of war", "call of duty"],
        "Category": ["action", "action", "sports", "adventure", "shooter"],
        "price":  [2500, 4000, 3400, 4888, 4000],

}
df = pd.DataFrame(data)

sns.countplot(x="Category", data=df)
plt.title("PS 5 Count Plot")
plt.show()


sns.barplot(x="Game", y="price", data=df)
plt.title("PS 5 Bar Plot")
plt.show()

plt.hist(df["price"], bins=5)
plt.title("PS 5 Histogram")
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()



"""!pip install seaborn

"""